### ISSUE TITLE
[Send Money] No need of selecting receiver and sender payment method.

### ISSUE THREAD

**Issue by Harshitha20-MCA** [pioneer-pay/pioneer-pay-microservices#11]
**Steps To Reproduce Bug**

1. Log In Into User Account
2. Enter Source and Destination
3. Enter Send Amount .
4. Do not select payment methods 
5. Click On 'Continue' Button

**Expected result**
We should not able to forward Without selecting sender and receiver payment method.

**Actual result**
Without selecting sender and receiver payment method we can continue.

**Comment by SupriyaRevanwar** [comment]
**Task done**
- Applied restriction on selecting payment method for both sender and receiver.
- Now user can't continue without selecting payment method for both sender and receiver.


![Image](https://github.com/pioneer-pay/pioneer-pay-microservices/assets/86201753/dcaa4590-0fb7-4dd0-85fb-de3fe8f23de2)



![Image](https://github.com/pioneer-pay/pioneer-pay-microservices/assets/86201753/fe409499-af21-4a5d-b6a0-bbac1f1a7afd)

**Comment by Mangesh-Shirodkar** [comment]
**Defect : DF_SM_08** has been successfully fixed and its working fine.
