### ISSUE TITLE
 As a user, I should be able to read notifications.

### ISSUE THREAD

**Issue by naundhe** [pioneer-pay/pioneer-pay-microservices#23]
**Definition of Done**

- When new notification come notify in app only how many unread notifications are there.
- User should be able to mark unread notification as read.

**Technical Details**

- Create one method in notification- service and its controller which return all unread notification.
- Create one method in notification-service and its controller to make unread notifications as read.

**Comment by naundhe** [comment]
- Need to add error handling properly.
- Add logging framework to show logs properly.
- Write Junit Test cases.

**Comment by Mangesh-Shirodkar** [comment]
- Feature: InApp Notification working fine with existing system.
- Automation Tests are successfully executed and passed.
- All identified bugs have been addressed and resolved.
