### ISSUE TITLE
As a user I want to view the reminders set by me

### ISSUE THREAD

**Issue by apurvagokhale29** [pioneer-pay/pioneer-pay-microservices#27]
**BE**
- Create service and controller for fetching all the reminders set by user

**FE**
- Create a reminder controller for fetching all the reminders set by user
- Create reminder.html page for viewing the reminders set by user

**Comment by Mangesh-Shirodkar** [comment]
- Testing is done for View Reminder feature and its working fine.


![Image](https://github.com/pioneer-pay/pioneer-pay-microservices/assets/68989269/daaeb213-dc9d-420b-92c6-b3297a05ae71)
