### ISSUE TITLE
As a user, I want to get a notification within the app whenever an action has been executed from the backend

### ISSUE THREAD

**Issue by naundhe** [pioneer-pay/pioneer-pay-microservices#4]
**Definition of Done** 

- Add Notification icon on navigation bar to display all notifications.
- Create table to store notifications.
- Create notification service.
- Add a limit to save notifications - older notification should delete automatically after some limit and show newer notifications.

**Technical Details**

- Create table notification add columns - `id`,`message`,`userId`,`timestamp`,`isRead`.
- Add notification-service and use in every service by using feign Client.
- Use notification-service in controller where some action being performed.

**Comment by naundhe** [comment]
- Need to add error handling properly.
- Add logging framework to show logs properly.
- Write Junit Test cases.

**Comment by Mangesh-Shirodkar** [comment]
- Feature: InApp Notification working fine with existing system.
- Automation Tests are successfully executed and passed.
- All identified bugs have been addressed and resolved.



![Image](https://github.com/pioneer-pay/pioneer-pay-microservices/assets/68989269/aeefbb0b-d45f-45f2-b5aa-48e90ebf4f9c)
