### ISSUE TITLE
[Registration] The system is currently accepting weak passwords during login. This needs to be addressed or fixed.

### ISSUE THREAD

**Issue by Harshitha20-MCA** [pioneer-pay/pioneer-pay-microservices#8]
**Steps to Reproduce:**
1.Navigate to the login page.
2.Enter a password that does not meet the defined strength criteria (e.g., lacks complexity, is too short).
3.Observe the system's acceptance of the weak password without any rejection or warning.

**Expected Result:**
The system should enforce password strength requirements, rejecting weak passwords and prompting users to choose a stronger password.

**Actual Result:**
 Weak passwords are accepted without any notification.

**Comment by Krushnamasal** [comment]
**Issue resolved**
